[package]
name = "hitdns"
version = "0.8.0"
edition = "2021"
description = "hitdns is a DNS forward server optimized for cache hit ratio and query latency."
license = "GPL-3.0"
authors = ["Delta4 <delta4chat@gmx.com>", "Your Name <you@example.com>"]
repository = "https://github.com/delta4chat/hitdns"
keywords = ["dns", "dns-over-https", "doh", "cache", "dns-server"]
categories = ["command-line-utilities", "network-programming", "caching", "web-programming::http-server", "web-programming::http-client"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["aws-lc-rs"]
aws-lc-rs = ["futures-rustls/aws-lc-rs"]
ring = ["futures-rustls/ring"]
rust-crypto = ["dep:rustls-rustcrypto"]
log4rs = ["dep:log4rs"]
bin = ["log4rs"]

[[bin]]
name = "hitdns"
required-features = ["bin"]

[[bin]]
name = "hitdns-test"
required-features = ["bin"]

[[bin]]
name = "hitdns-h2test"
required-features = ["bin"]

[dependencies]
ahash = { version = "0.8.12", default-features = false, features = ["atomic-polyfill", "compile-time-rng"] }
async-channel = "2.3.1"
asyncute = { version = "0.0.7", default-features = false, features = ["crossbeam-channel"] }
bytes = "1.10.1"
country-code-enum = "0.2.0"
event-listener = { version = "5.4.0", features = ["portable-atomic"] }
heapless = { version = "0.8.0", features = ["portable-atomic"] }
hickory-proto = { version = "0.25.2", default-features = false, features = ["std"] }
http-types = { version = "2.12.0", default-features = false }
log = { version = "0.4.27", features = ["std"] }
moka = { version = "0.12.10", features = ["future"] }
once_cell = { version = "1.21.3", features = ["portable-atomic", "parking_lot"] }
parking = "2.2.1"
portable-atomic = { version = "1.11.1", features = ["std"] }
scc2 = "2.4.4"
sdd = "3.0.8"
sled = { version = "0.34.7", features = ["lock_free_delays", "compression", "backtrace"] }
smoltimeout = "0.6.3"

# TODO publish once this crate from alpha stage to beta
non-tokio = { path = "../toolset/non-tokio" }

async-net = "2.0.0"
async-io = "2.4.1"

futures-rustls = { version = "0.26.0", default-features = false, features = ["logging"] }
h2 = { version = "0.4.10", default-features = false }

anypki = "0.2.1"
mozilla-root-ca = { version = ">=0.0.0", features = ["std", "rustls"] }
rustls-rustcrypto = { optional = true, version = "0.0.2-alpha" }
rustls-webpki = "0.103.3"
http = "1.3.1"
futures-lite = "2.6.0"
fastrand = "2.3.0"
nohash = "0.2.0"
directories = "6.0.0"
dns-stamp-parser = { version = "3.0.1", default-features = false }
log4rs = { version = "1.3.0", default-features = false, features = ["console_appender", "rolling_file_appender", "gzip", "background_rotation", "compound_policy", "fixed_window_roller", "size_trigger"], optional = true }

[build-dependencies]

[profile.dev]
panic = "unwind"
opt-level = 2
lto = "off"
#strip = "none"
codegen-units = 256
overflow-checks = true
debug-assertions = true
debug = "limited"
incremental = true

[profile.mydev]
inherits = "dev"
panic = "unwind"
opt-level = 0
lto = "off"
#strip = "none"
codegen-units = 1048576
overflow-checks = true
debug-assertions = true
debug = "full"
incremental = false

[profile.release]
panic = "unwind"
opt-level = 3
lto = true
strip = true
codegen-units = 1
overflow-checks = true
debug-assertions = false
debug = 1
incremental = false


