[package]
name = "hitdns"
version = "0.3.3"
edition = "2021"
description = "hitdns is a DNS forward server optimized for cache hit ratio and query latency."
license = "GPL-3.0"
authors = ["Delta4 <delta4chat@gmx.com>", "Your Name <you@example.com>"]
repository="https://github.com/delta4chat/hitdns"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
async-lock = "3.3.0"
async-tls = "0.13.0"
async-trait = "0.1.77"
bincode = "1.3.3"
bytes = "1.5.0"
clap = { version = "4.4.18", features = ["derive", "debug"] }
directories = "5.0.1"
env_logger = "0.11.0"
hickory-proto = { version = "0.24.0", default-features = false }
hyper = { version = "0.14.21", default-features = false, features = ["client"] }
log = "0.4.20"
once_cell = "1.19.0"
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls"] }
scc = "2.0.11"
serde = { version = "1.0.195", features = ["derive"] }
smol = "2.0.0"
smol-timeout = "0.6.0"

#smolscale = { version = "0.4.4", features = ["preempt"] }
#smolscale = { git = "https://github.com/delta4chat/smolscale", features = ["preempt"] }
smolscale = { path = "./lib/smolscale", features = ["preempt"] }

sqlx = { version = "0.7.3", features = ["runtime-async-std", "sqlite"], default-features = false }

[profile.dev]
panic = "unwind"
opt-level = 2
lto = "off"
#strip = "none"
codegen-units = 1
overflow-checks = true
debug-assertions = true
debug = "limited"
incremental = false

[profile.release]
panic = "unwind"
opt-level = 2
#lto = true
#strip = "none"
codegen-units = 1
overflow-checks = true
debug-assertions = false
#debug = "limited"
incremental = false

