[package]
name = "hitdns"
version = "0.1.0"
edition = "2021"
description = "hitdns is a DNS server optimized for cache hit ratio and query latency. "

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
async-lock = "3.3.0"
async-tls = "0.13.0"
async-trait = "0.1.77"
bincode = "1.3.3"
bytes = "1.5.0"
dashmap = "5.5.3"
directories = "5.0.1"
env_logger = "0.11.0"
hickory-proto = { version = "0.24.0", default-features = false, features = ["serde-config", "serde"] }
hyper = { version = "0.14.21", default-features = false, features = ["client"] }
log = "0.4.20"
once_cell = "1.19.0"
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0.195", features = ["derive"] }
smol = "2.0.0"
smol-timeout = "0.6.0"
smolscale = "0.4.4"
sqlx = { version = "0.7.3", features = ["runtime-async-std", "sqlite"], default-features = false }

