//! DNS Entry (response)

use crate::{
    *,
    query::{self, *},
    upstream::*,
    util::*,
    config::*,
};

/// the source of DNS response.
/// * Unknown: where is this response from is unclear.
/// * Plugin(name_of_plugin): this response is generated by callable plugins.
/// * Internet(upstream_server): this response is from public DNS upstream.
/// * Hosts(path_to_hosts_txt): this response is based on some hosts.txt files located in system path or user-defined path.
/// * Local(lan_ip_port): this response is from router, gateway, or another kind of LAN domains.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum DNSResponseSource {
    Plugin(u32) = Self::PLUGIN,
    Hosts(String) = Self::HOSTS,
    Local(SocketAddr) = Self::LOCAL,
    Internet(Result<Arc<dyn DNSUpstream>, Url>) = Self::INTERNET,
    Unknown = Self::UNKNOWN,
}

impl DNSResponseSource {
    pub const PLUGIN:   u8 = b'P';
    pub const HOSTS:    u8 = b'H';
    pub const LOCAL:    u8 = b'L';
    pub const INTERNET: u8 = b'I';
    pub const UNKNOWN:  u8 = u8::MAX;

    pub fn variant(&self) -> u8 {
        match self {
            Self::Plugin(_) => Self::PLUGIN,
            Self::Hosts(_) => Self::HOSTS,
            Self::Local(_) => Self::LOCAL,
            Self::Internet(_) => Self::INTERNET,
            Self::Unknown => Self::UNKNOWN,
        }
    }

    /// serialize DNSResponseSource to bytes.
    ///
    /// format (all multi-bytes numeric field is encoded in big endian):
    /// ```text
    /// +-----------------------+---------+----------------+
    /// |  Field Name           | Unit    | Length (Bytes) |
    /// +-----------------------+---------+----------------+
    /// | Kind                  | Byte    | 1              |
    /// +-----------------------+---------+----------------+
    /// | Data (Kind-specific)  | N/A     | ?              |
    /// +-----------------------+---------+----------------+
    /// ```
    ///
    /// * if Kind is Plugin:
    /// ```text
    /// +-----------------------+---------+----------------+
    /// |  Field Name           | Unit    | Length (Bytes) |
    /// +-----------------------+---------+----------------+
    /// | Data (Plugin ID)      | Integer | 4              |
    /// +-----------------------+---------+----------------+
    /// ```
    ///
    /// * if Kind is Hosts:
    /// ```text
    /// +-----------------------+---------+----------------+
    /// |  Field Name           | Unit    | Length (Bytes) |
    /// +-----------------------+---------+----------------+
    /// | Data 1 (Path Length)  | Integer | 2              |
    /// +-----------------------+---------+----------------+
    /// | Data 2 (Path)         | String  | variable       |
    /// +-----------------------+---------+----------------+
    /// ```
    ///
    /// * if Kind is Local:
    /// ```text
    /// +-----------------------+---------+----------------+
    /// |  Field Name           | Unit    | Length (Bytes) |
    /// +-----------------------+---------+----------------+
    /// | Data 1 (IP Length)    | Byte    | 1              |
    /// +-----------------------+---------+----------------+
    /// | Data 2 (IP Address)   | Integer | 4 or 16        |
    /// +-----------------------+---------+----------------+
    /// | Data 3 (Port)         | Integer | 2              |
    /// +-----------------------+---------+----------------+
    /// ```
    ///
    /// * if Kind is Internet:
    /// ```text
    /// +-----------------------+---------+----------------+
    /// |  Field Name           | Unit    | Length (Bytes) |
    /// +-----------------------+---------+----------------+
    /// | Data 1 (URL Length)   | Integer | 2              |
    /// +-----------------------+---------+----------------+
    /// | Data 2 (URL)          | String  | variable       |
    /// +-----------------------+---------+----------------+
    /// ```
    ///
    /// * if Kind is Unknown, it's no data fields.
    pub fn encode(&self, out: &mut Vec<u8>) -> usize {
        let mut written = 0;
        match self {
            Self::Plugin(id) => {
                out.reserve(1 + 4);

                out.push(Self::PLUGIN);
                written += 1;

                let id = id.to_be_bytes();
                out.extend(&id);
                written += id.len();
            },
            Self::Hosts(path) => {
                let path = path.as_bytes();

                let path_len = path.len();
                if path_len > (u16::MAX as usize) {
                    log::warn!("DNSResponseSource::encode(): unexpected hosts path length too long!");
                    return 0;
                }

                out.reserve(1 + 2 + path_len);

                out.push(Self::HOSTS);
                written += 1;

                out.extend((path_len as u16).to_be_bytes());
                written += 2;

                out.extend(path);
                written += path_len;
            },
            Self::Local(addr) => {
                match addr.ip() {
                    IpAddr::V4(ip4) => {
                        let ip4 = ip4.octets();
                        assert!(ip4.len() == 4);

                        out.reserve(1 + 1 + 4 + 2);

                        out.push(Self::LOCAL);
                        written += 1;

                        out.push(4);
                        written += 1;

                        out.extend(ip4);
                        written += 4;
                    },
                    IpAddr::V6(ip6) => {
                        let ip6 = ip6.octets();
                        assert!(ip6.len() == 16);

                        out.reserve(1 + 1 + 16 + 2);

                        out.push(Self::LOCAL);
                        written += 1;

                        out.push(16);
                        written += 1;

                        out.extend(ip6);
                        written += 16;
                    },
                }

                out.extend(addr.port().to_be_bytes());
                written += 2;
            },
            Self::Internet(peer) => {
                let mut url =
                    match peer {
                        Ok(upstream) => {
                            upstream.protocol().url().to_string().into_bytes()
                        },
                        Err(url) => {
                            url.to_string().into_bytes()
                        }
                    };

                let url_len = url.len();
                if url_len > (u16::MAX as usize) {
                    log::warn!("DNSResponseSource::encode(): unexpected url length too long!");
                    return 0;
                }

                out.reserve(1 + 2 + url_len);

                out.push(Self::INTERNET);
                written += 1;

                out.extend((url_len as u16).to_be_bytes());
                written += 2;

                out.append(&mut url);
                written += url_len;
            },
            Self::Unknown => {
                out.push(Self::UNKNOWN);
                written += 1;
            },
        }

        written
    }

    pub fn decode<B: AsRef<[u8]>>(bytes: B) -> std::io::Result<Self> {
        let mut bytes = bytes.as_ref();

        let bytes_len = bytes.len();
        if bytes_len < 1 {
            return err_invalid_input("DNSResponseSource too short!");
        }

        let kind = bytes[0];
        bytes = &bytes[1..];

        let this =
            match kind {
                Self::PLUGIN => {
                    if bytes.len() < 4 {
                        return err_invalid_input("DNSResponseSource: Plugin ID too short!");
                    }
                    let id = u32::from_be_bytes(asyncute::slice_to_array(bytes, 0).unwrap());

                    Self::Plugin(id)
                },
                Self::HOSTS => {
                    if bytes.len() < 2 {
                        return err_invalid_input("DNSResponseSource: Hosts Path Length too short!");
                    }

                    let len = u16::from_be_bytes([ bytes[0], bytes[1] ]) as usize;
                    bytes = &bytes[2..];

                    if bytes.len() < len {
                        return err_invalid_input("DNSResponseSource: Hosts Path too short!");
                    }
                    let path =
                        // 1. first zero-copy decode UTF-8 string.
                        // 2. only clone if success, so avoid some attacks.
                        match core::str::from_utf8(&bytes[..len]) {
                            Ok(p) => {
                                p.to_string()
                            },
                            _ => {
                                return err_invalid_input("DNSResponseSource: Hosts Path is not valid UTF-8 encoded!");
                            }
                        };

                    Self::Hosts(path)
                },
                Self::LOCAL => {
                    if bytes.len() < (1 + 4 + 2) {
                        return err_invalid_input("DNSResponseSource: Local data fields is too short!");
                    }

                    let ip_len = bytes[0];
                    bytes = &bytes[1..];

                    let ip = 
                        match ip_len {
                            4 => {
                                if bytes.len() < 4 {
                                    return err_invalid_input("DNSResponseSource: Local IP4 too short!");
                                }
                                let ip4 = Ipv4Addr::from(asyncute::slice_to_array(bytes, 0).unwrap());
                                bytes = &bytes[4..];
                                IpAddr::V4(ip4)
                            },
                            16 => {
                                if bytes.len() < 16 {
                                    return err_invalid_input("DNSResponseSource: Local IP6 too short!");
                                }
                                let ip6 = Ipv6Addr::from(asyncute::slice_to_array(bytes, 0).unwrap());
                                bytes = &bytes[16..];
                                IpAddr::V6(ip6)
                            },
                            _ => {
                                return err_invalid_input("DNSResponseSource: Local IP Length unknown!");
                            }
                        };

                    if bytes.len() < 2 {
                        return err_invalid_input("DNSResponseSource: Local Port is too short!");
                    }

                    let port = u16::from_be_bytes([ bytes[0], bytes[1] ]);

                    Self::Local(SocketAddr::new(ip, port))
                },
                Self::INTERNET => {
                    if bytes.len() < 2 {
                        return err_invalid_input("DNSResponseSource: Internet Upstream URL Length too short!");
                    }

                    let len = u16::from_be_bytes([ bytes[0], bytes[1] ]) as usize;
                    bytes = &bytes[2..];

                    if bytes.len() < len {
                        return err_invalid_input("DNSResponseSource: Internet Upstream URL too short!");
                    }
                    let url =
                        // 1. first zero-copy decode UTF-8 string.
                        // 2. only parse if success, so avoid some attacks.
                        match core::str::from_utf8(&bytes[..len]) {
                            Ok(u) => {
                                match Url::parse(u) {
                                    Ok(v) => v,
                                    _ => {
                                        return err_invalid_input("DNSResponseSource: Internet Upstream URL is unable parsed as url::Url!");
                                    }
                                }
                            },
                            _ => {
                                return err_invalid_input("DNSResponseSource: Internet Upstream URL is not valid UTF-8 encoded!");
                            }
                        };

                    Self::Internet(Err(url))
                },
                Self::UNKNOWN => {
                    Self::Unknown
                },
                _ => {
                    return err_invalid_input("DNSResponseSource: Kind is unknown!");
                }
            };

        Ok(this)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct DNSEntry {
    /// whole DNS Response
    pub response: Arc<dns::Message>,

    /// expire timestamp of this entry
    pub expire_time: SystemTime,

    /// this DNS response is from which source?
    pub source: DNSResponseSource,
}

impl DNSEntry {
    /// parse from wire format.
    pub fn parse<B: AsRef<[u8]>>(wire: B, source: DNSResponseSource) -> std::io::Result<Self> {
        let wire = wire.as_ref();
        let msg: dns::Message = dns::BinDecodable::from_bytes(wire).map_err(invalid_input)?;
        Ok(Self::new(msg, source))
    }

    /// create from DNS Message.
    pub fn new(msg: dns::Message, source: DNSResponseSource) -> Self {
        Self::new_arc(Arc::new(msg), source)
    }

    /// create from DNS Message (Arc-wrapped).
    pub fn new_arc(response: Arc<dns::Message>, source: DNSResponseSource) -> Self {
        let conf = CacheConfig::global();
        let min_ttl = conf.min_ttl();
        let max_ttl = conf.max_ttl();

        let mut ttl = max_ttl;
        let mut it;
        for record in response.all_sections() {
            it = record.ttl();
            if it < ttl {
                ttl = it;
            }
        }
        
        if ttl > max_ttl {
            ttl = max_ttl;
        } else if ttl < min_ttl {
            ttl = min_ttl;
        }

        let expire_time = SystemTime::now() + Duration::from_secs(ttl as u64);

        Self {
            response,
            expire_time,
            source,
        }
    }

    /// Serialize to bytes for store in databases.
    /// * DNS response sometimes too large, so need to store in heap.
    ///
    /// format (all multi-bytes numeric field is encoded in big endian):
    /// * see
    /// ```text
    /// +-----------------------+---------+----------------+
    /// |  Field Name           | Unit    | Length (Bytes) |
    /// +-----------------------+---------+----------------+
    /// | Version               | Byte    | 1              |
    /// +-----------------------+---------+----------------+
    /// | Expire Unix Timestamp | Seconds | 8              |
    /// +-----------------------+---------+----------------+
    /// | DNS Response Length   | Integer | 2              |
    /// +-----------------------+---------+----------------+
    /// | DNS Response          | Length  | variable       |
    /// +-----------------------+---------+----------------+
    /// | DNS Upstream Source   | Source  | variable       |
    /// +-----------------------+---------+----------------+
    /// ```
    pub fn encode(&self) -> Vec<u8> {
        let mut resp: Vec<u8> = self.response.to_vec().expect("unexpectedly dns::Message invalid");
        let resp_len = resp.len();

        let mut out_len = 1 + 8 + 2 + resp_len;
        let mut out = Vec::with_capacity(out_len);

        out.push(query::serialized::VERSION);
        out.extend(self.expire_time.duration_since(SystemTime::UNIX_EPOCH).expect("system time earlier unix epoch!?").as_secs().to_be_bytes());
        out.extend(resp_len.to_be_bytes());
        out.append(&mut resp);

        out_len += self.source.encode(&mut out);

        assert_eq!(out.len(), out_len);
        out
    }

    /// decode DNSEntry from serialized format.
    pub fn decode<B: AsRef<[u8]>>(bytes: B) -> std::io::Result<Self> {
        let mut bytes = bytes.as_ref();

        let bytes_len = bytes.len();
        if bytes_len < (1 + 8 + 2) {
            return err_invalid_input("serialized DNSEntry too short!");
        }

        let version = bytes[0];
        if version != query::serialized::VERSION {
            return err_invalid_input("unknown DNSEntry serialization version");
        }
        bytes = &bytes[1..];

        let expire_time =
            SystemTime::UNIX_EPOCH.checked_add(
                Duration::from_secs(
                    u64::from_be_bytes(asyncute::slice_to_array(bytes, 0).unwrap())
                )
            ).expect("timestamp overflow!");
        bytes = &bytes[8..];

        let resp_len = u16::from_be_bytes([ bytes[0], bytes[1] ]) as usize;
        bytes = &bytes[2..];

        if bytes.len() < resp_len {
            return err_invalid_input("DNSEntry: Response too short!");
        }

        let response = Arc::new(dns::Message::from_vec(&bytes[..resp_len]).map_err(invalid_input)?);
        bytes = &bytes[resp_len..];

        let source = DNSResponseSource::decode(bytes).unwrap_or(DNSResponseSource::Unknown);

        Ok(Self {
            response,
            expire_time,
            source,
        })
    }
}
