//! DNS Entry (response)

use crate::{
    *,
    query::{self, *},
    upstream::*,
    util::*,
    config::*,
};

/// the source of DNS response.
/// * Unknown: where is this response from is unclear.
/// * Plugin(name_of_plugin): this response is generated by callable plugins.
/// * Internet(upstream_server): this response is from public DNS upstream.
/// * Hosts(path_to_hosts_txt): this response is based on some hosts.txt files located in system path or user-defined path.
/// * Local(lan_ip_port): this response is from router, gateway, or another kind of LAN domains.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum DNSResponseSource {
    Plugin(u32) = Self::PLUGIN,
    Hosts(String) = Self::HOSTS,
    Local(SocketAddr) = Self::LOCAL,
    Internet(Arc<dyn DNSUpstream>) = Self::INTERNET,
    Unknown = Self::UNKNOWN,
}

impl DNSResponseSource {
    pub const PLUGIN: u8 = 1;
    pub const HOSTS: u8 = 2;
    pub const LOCAL: u8 = 3;
    pub const INTERNET: u8 = 4;
    pub const UNKNOWN: u8 = u8::MAX;

    pub fn variant(&self) -> u8 {
        match self {
            Self::Plugin(_) => Self::PLUGIN,
            Self::Hosts(_) => Self::HOSTS,
            Self::Local(_) => Self::LOCAL,
            Self::Internet(_) => Self::INTERNET,
            Self::Unknown => Self::UNKNOWN,
        }
    }

    pub fn to_bytes(&self, out: &mut Vec<u8>) -> usize {
        let mut written = 0;
        match self {
            Self::Plugin(id) => {
                out.push(Self::PLUGIN);
                written += 1;

                let id = id.to_be_bytes();
                out.extend(&id);
                written += id.len();
            },
            Self::Hosts(path) => {
                let path = path.as_bytes();

                let path_len = path.len();
                if path_len > (u16::MAX as usize) {
                    return 0;
                }

                out.push(Self::HOSTS);
                written += 1;

                out.push((path_len as u16).to_be_bytes());
                written += 2;

                out.push(path);
                written += path_len;
            },
            Self::Local(addr) => {
                out.push(Self::LOCAL);
                written += 1;

                match addr.ip() {
                    IpAddr::V4(ip4) => {
                        let ip4 = ip4.octets();
                        assert!(ip4.len() == 4);

                        out.push(4);
                        written += 1;

                        out.extend(ip4);
                        written += 4;
                    },
                    IpAddr::V6(ip6) => {
                        let ip6 = ip6.octets();
                        assert!(ip6.len() == 16);

                        out.push(16);
                        written += 1;

                        out.push(ip6);
                        written += 16;
                    },
                }

                out.extend(addr.port().to_be_bytes());
                written += 2;
            },
            Self::Internet(upstream) => {
                out.push(Self::INTERNET);
                written += 1;


            },
            Self::Unknown => {
                out.push(Self::UNKNOWN);
                written += 1;
            },
        }

        written
    }

    pub fn from_bytes<B: AsRef<[u8]>>(bytes: B) -> std::io::Result<()> {
        todo!()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DNSEntry {
    /// whole DNS Response
    pub response: Arc<dns::Message>,

    /// expire timestamp of this entry
    pub expire_time: SystemTime,

    /// this DNS response is from which source?
    pub source: DNSResponseSource,
}

impl DNSEntry {
    /// parse from wire format.
    pub fn parse<B: AsRef<[u8]>>(wire: B, source: DNSResponseSource) -> std::io::Result<Self> {
        let wire = wire.as_ref();
        let msg: dns::Message = dns::BinDecodable::from_bytes(wire).map_err(invalid_input)?;
        Ok(Self::new(msg, source))
    }

    /// create from DNS Message.
    pub fn new(msg: dns::Message, source: DNSResponseSource) -> Self {
        Self::new_arc(Arc::new(msg), source)
    }

    /// create from DNS Message (Arc-wrapped).
    pub fn new_arc(response: Arc<dns::Message>, source: DNSResponseSource) -> Self {
        let conf = CacheConfig::global();
        let min_ttl = conf.min_ttl();
        let max_ttl = conf.max_ttl();

        let mut ttl = max_ttl;
        let mut it;
        for record in response.all_sections() {
            it = record.ttl();
            if it < ttl {
                ttl = it;
            }
        }
        
        if ttl > max_ttl {
            ttl = max_ttl;
        } else if ttl < min_ttl {
            ttl = min_ttl;
        }

        let expire_time = SystemTime::now() + Duration::from_secs(ttl as u64);

        Self {
            response,
            expire_time,
            source,
        }
    }

    /// Serialize to bytes for store in databases.
    /// * DNS response sometimes too large, so need to store in heap.
    ///
    /// format:
    /// ```text
    /// +---------------------+----------------+
    /// |  Field Name         | Length (Bytes) |
    /// +---------------------+----------------+
    /// |                     |                |
    /// +---------------------+----------------+
    /// ```
    /// 
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut resp: Vec<u8> = self.response.to_vec().expect("unexpectedly dns::Message invalid");
        let resp_len = resp.len();

        let out_len = 1 + 8 + 2 + resp_len;
        let mut out = Vec::with_capacity(out_len);

        out.push(VERSION);
        out.extend(self.expire_time.duration_since(SystemTime::UNIX_EPOCH).expect("system time earlier unix epoch!?").as_secs().to_be_bytes());
        out.extend(resp_len.to_be_bytes());
        out.append(&mut resp);

        assert_eq!(out.len(), out_len);
        out
    }
}
