//! DNS Entry (response)

use crate::{
    *,
    query::*,
    upstream::*,
    helper::*,
    config::*,
};

/// the source of DNS response.
/// * Unknown: where is this response from is unclear.
/// * Plugin(name_of_plugin): this response is generated by callable plugins.
/// * Internet(upstream_server): this response is from public DNS upstream.
/// * Hosts: this response is based on some hosts.txt files located in system path or user-defined path.
/// * Local: this response is from router, gateway, or another kind of LAN domains.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DNSResponseSource {
    Unknown,
    Plugin(u64),
    Internet(Arc<dyn DNSUpstream>),
    Hosts,
    Local,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DNSEntry {
    /// whole DNS Response
    pub response: Arc<dns::Message>,

    /// expire timestamp of this entry
    pub expire_time: SystemTime,

    /// this DNS response is from which source?
    pub source: DNSResponseSource,
}

impl DNSEntry {
    pub fn parse<B: AsRef<[u8]>>(wire: B, source: DNSResponseSource) -> std::io::Result<Self> {
        let wire = wire.as_ref();
        let msg: dns::Message = dns::BinDecodable::from_bytes(wire).map_err(invalid_input)?;
        Ok(Self::new(msg, source))
    }

    pub fn new(msg: dns::Message, source: DNSResponseSource) -> Self {
        Self::new_arc(Arc::new(msg), source)
    }

    pub fn new_arc(response: Arc<dns::Message>, source: DNSResponseSource) -> Self {
        let conf = CacheConfig::global();
        let min_ttl = conf.min_ttl();
        let max_ttl = conf.max_ttl();

        let mut ttl = max_ttl;
        let mut it;
        for record in response.all_sections() {
            it = record.ttl();
            if it < ttl {
                ttl = it;
            }
        }
        
        if ttl > max_ttl {
            ttl = max_ttl;
        } else if ttl < min_ttl {
            ttl = min_ttl;
        }

        let expire_time = SystemTime::now() + Duration::from_secs(ttl as u64);

        Self {
            response,
            expire_time,
            source,
        }
    }
}
